import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppSideBar from "@/widgets/app/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-[max-content_1fr] w-full">
          <AppSideBar />
          <div className="px-4 md:px-10 pb-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
